[package]
name = "low-level"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmtime = "0.39.1"

[dev-dependencies]
wasmtime-wasi = "0.39.1"
